### ISSUE TITLE
Issue loading Jupiter SDK

### ISSUE THREAD

**Issue by Corey0193** [ARBProtocol/solana-jupiter-bot#10]
Thanks so much for making this! I'm having this issue with loading Jupiter though:

 Config loaded!
 Loading Jupiter SDK...Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
 Loading Jupiter SDK...Server responded with 429 Too Many Requests.  Retrying after 1000ms delay...
 Loading Jupiter SDK...Server responded with 429 Too Many Requests.  Retrying after 2000ms delay...
 Loading Jupiter SDK...Server responded with 429 Too Many Requests.  Retrying after 4000ms delay...
 Setting up failed!
        Loading Jupiter SDK...
ERROR: Missing 5Z66YYYaTmmx1R4mATAGLSc8aV4Vfy5tNdJQzk1GP9RF
Error: Missing 5Z66YYYaTmmx1R4mATAGLSc8aV4Vfy5tNdJQzk1GP9RF
    at WhirlpoolAmm.update (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\node_modules\@jup-ag\core\dist\core.cjs.development.js:4423:38)
    at prefetchAmms (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\node_modules\@jup-ag\core\dist\core.cjs.development.js:2876:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getAllAmms (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\node_modules\@jup-ag\core\dist\core.cjs.development.js:7135:3)
    at async Function.fetchTokenRouteSegments (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\node_modules\@jup-ag\core\dist\core.cjs.development.js:8747:18)     
    at async Promise.all (index 0)
    at async Function.load (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\node_modules\@jup-ag\core\dist\core.cjs.development.js:8612:52)
    at async setup (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\src\setup.js:69:19)
    at async run (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\src\bot.js:395:39)

        Exit time:  2022-08-07, 11:08:30 a.m. 
                > Cache saved to ./temp/cache.json 
                > Trade history saved to ./temp/tradeHistory.json 
        Exit Done!

**Comment by pmioduszewski** [comment]
Hi Corey0193 ^^
This error is related to the RPC server, did you use https://arbprotocol.genesysgo.net?

**Comment by Corey0193** [comment]
Hmm.. I've set it as my default RPC, now I have this error:

```
✖ No routes found. Something is wrong!
✖ Computing routes failed!

ERROR: Cannot read properties of undefined (reading 'outAmountWithSlippage')
TypeError: Cannot read properties of undefined (reading 'outAmountWithSlippage')
    at getInitialOutAmountWithSlippage (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\src\setup.js:116:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (C:\Users\16136\Documents\Arbbot\solana-jupiter-bot\src\bot.js:407:34)
Closing connections...  WAIT! 
Press [Ctrl]+[C] to force exit
ERROR: No routes found or something is wrong with RPC / Jupiter! 
Closing connections...  WAIT! 
Press [Ctrl]+[C] to force exit

        Exit time:  2022-08-11, 9:31:25 p.m. 
                > Cache saved to ./temp/cache.json 
                > Trade history saved to ./temp/tradeHistory.json 
        Exit Done! 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```


Sorry for the noob questions :/

**Comment by UsamaLion** [comment]
![image](https://user-images.githubusercontent.com/62137456/189474320-3d7e1094-a7ee-4346-b7f0-94bcac36da35.png)

I'm having this error and working on this for while but unable to find any solution please help me
