### ISSUE TITLE
Problem with pingpong trading

### ISSUE THREAD

**Issue by a040900** [ARBProtocol/solana-jupiter-bot#2]
Hi, I have a problem when running this bot.
When I trade USDT -> USDC and the system also wanna try to make a profit, it always notifies the error message below:

```
Error: Account info CUQecDVPSLXwWvUAPNTjtGb46vmteuMdqKqyFQnkPrLc missing
    at /home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:2508:13
    at Array.map (<anonymous>)
    at mapAddressToAccountInfos (/home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:2504:34)
    at SerumAmm.update (/home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:2838:48)
    at /home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:5460:11
    at Map.forEach (<anonymous>)
    at fetchAccountInfos (/home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:5459:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Jupiter.computeRoutes (/home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:6076:7)
```
Also have a problem on USDC -> USDT, the error message is :
```
Error: Account info 8sfGm6jsFTAcb4oLuqMKr1xNEBd5CXuNPAKZEdbeezA missing
    at /home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:2508:13
    at Array.map (<anonymous>)
    at mapAddressToAccountInfos (/home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:2504:34)
    at SerumAmm.update (/home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:2838:48)
    at /home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:5460:11
    at Map.forEach (<anonymous>)
    at fetchAccountInfos (/home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:5459:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Jupiter.computeRoutes (/home/aliven2023/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.development.js:6076:7)
    at async pingpongMode (/home/aliven2023/solana-jupiter-bot/src/bot.js:213:18)

```
My environment is Debian 11 , yarn 1.22.19, node 16.16

**Comment by pmioduszewski** [comment]
Hi, this error is related to RPC.
Sometimes RPC can time out or empty/bad response then U get this error.
Try to change the RPC URL to different one. e.g
`https://arbprotocol.genesysgo.net`

**Comment by a040900** [comment]
Thank you!
