### ISSUE TITLE
Problem with yarn start

### ISSUE THREAD

**Issue by a040900** [ARBProtocol/solana-jupiter-bot#5]
Hi, after I update the new of this bot, I got this error when I type "yarn start"
But is okay if I back to using the old one.
I'm not sure about this situation is wrong with my environment or not?
Thank you

The Error Message is:
```
/home/aliven2023/solana-jupiter-bot/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: ENOENT: no such file or directory, open './config.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/home/aliven2023/solana-jupiter-bot/src/cache.js:2:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/aliven2023/solana-jupiter-bot/src/utils.js:3:15) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './config.json'
}
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pmioduszewski** [comment]
I was able to reproduce this issue. Will check it soon. Thanks!

**Comment by pmioduszewski** [comment]
I've reopened cuz I'm not sure that You can comment on the closed issue

**Comment by a040900** [comment]
Hi, I had already tested it, and is all fine right now. 🙂
Thanks

**Comment by a040900** [comment]
Hi, this problem had shown again after I updated it 3 days ago.

**Comment by pmioduszewski** [comment]
Yeah, I forgot to push changes from my local 🤦
