### ISSUE TITLE
stuck on this error, please help

### ISSUE THREAD

**Issue by randomnodes** [ARBProtocol/solana-jupiter-bot#61]
Been messing around with this for awhile and this is as far as I can get. Any help would be appreciated. 

✔ Config loaded!
✖ Setting up failed!
 	Loading Jupiter SDK...
ERROR: Expected the value to satisfy a union of `type | type`, but received: [object Object]
StructError: Expected the value to satisfy a union of `type | type`, but received: [object Object]
    at validate (/home/solana-jupiter-bot/node_modules/superstruct/lib/index.cjs:363:19)
    at Object.create (/home/solana-jupiter-bot/node_modules/superstruct/lib/index.cjs:319:18)
    at Connection.getTokenAccountsByOwner (/home/solana-jupiter-bot/node_modules/@solana/web3.js/lib/index.cjs.js:5890:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Dt (/home/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.production.min.js:1:85879)
    at async Promise.all (index 2)
    at async Ht.load (/home/solana-jupiter-bot/node_modules/@jup-ag/core/dist/core.cjs.production.min.js:1:99751)
    at async setup (/home/solana-jupiter-bot/src/bot/setup.js:75:19)
    at async run (/home/solana-jupiter-bot/src/bot/index.js:398:39)

**Comment by AntoFab1** [comment]
I have same issue

**Comment by RedHatMining** [comment]
yeah so the Jupiter SDK is out of date

**Comment by randomnodes** [comment]
what file and line can I change to update to current Jupiter SDK?

**Comment by RedHatMining** [comment]
there are a lot of things you will have to change i am currently working on it and if u see the repo on my profile at some point it will be done
